version: "3.8"

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mvc_framework'
      MYSQL_USER: 'amir'
      MYSQL_PASSWORD: 'changeMe'
      MYSQL_ROOT_PASSWORD: 'changeMe'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data:


#  mongo:
#    container_name: mongodb
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example