version: "3.8"

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example